# Generated by Django 4.1.2 on 2022-10-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_organization_product_customuser_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='organization',
            field=models.ManyToManyField(to='app1.organization'),
        ),
    ]
